// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IEosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    IIcRoundBookmarkAdd: typeof import('~icons/ic/round-bookmark-add')['default']
    IIcRoundBookmarks: typeof import('~icons/ic/round-bookmarks')['default']
    IIcRoundCheckCircle: typeof import('~icons/ic/round-check-circle')['default']
    IIcRoundCheckCircleOutline: typeof import('~icons/ic/round-check-circle-outline')['default']
    IIcRoundClose: typeof import('~icons/ic/round-close')['default']
    IIcRoundDarkMode: typeof import('~icons/ic/round-dark-mode')['default']
    IIcRoundGTranslate: typeof import('~icons/ic/round-g-translate')['default']
    IIcRoundHistory: typeof import('~icons/ic/round-history')['default']
    IIcRoundLightMode: typeof import('~icons/ic/round-light-mode')['default']
    IIcRoundPlus: typeof import('~icons/ic/round-plus')['default']
    IIcRoundRemoveCircleOutline: typeof import('~icons/ic/round-remove-circle-outline')['default']
    IIcRoundRemoveRedEye: typeof import('~icons/ic/round-remove-red-eye')['default']
    IIcRoundSearch: typeof import('~icons/ic/round-search')['default']
    IIcRoundSearchOff: typeof import('~icons/ic/round-search-off')['default']
    IIcRoundSettings: typeof import('~icons/ic/round-settings')['default']
    IIcRoundVolumeUp: typeof import('~icons/ic/round-volume-up')['default']
    IIcRoundWifiOff: typeof import('~icons/ic/round-wifi-off')['default']
    IPhCircleDashedBold: typeof import('~icons/ph/circle-dashed-bold')['default']
  }
}

export {}
